services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=syed
      - POSTGRES_PASSWORD=abc123
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Users/syedsaif/mycode/makeitwork/django_docker_project
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=syed
      - POSTGRES_PASSWORD=abc123
    depends_on:
      - db